Use regular stdout/stderr logging instead of standalone file. Using a stanalone file is more problematic as the filepath may not exist.
There are some errors we see, e.g.:
PermissionError: [Errno 13] Permission denied: '/tmp/intakegfdl.log'

that this update should fix